pipelines:
  branches:
    master:
      - step:
          script:
            - curl -I -X POST -u "$JenkinsUser:$JenkinsAuthToken" "$JenkinsBaseUrl?BitBucketRepoName=$BITBUCKET_REPO_SLUG&Branch=$BITBUCKET_BRANCH&Technology=$Technology"